---
title: "Test R Markdown Knit"
output: pdf_document
---


```{r echo=TRUE}
install.packages("stringr")
library("stringr")
install.packages("Metrics")
library(Metrics)
install.packages("ggplot2")
library(ggplot2)
```


Data Cleaning
```{r echo=TRUE}
trainingCopy <- training
wellbore <- str_split(trainingCopy$wellbore_chev_no_id, '_')
class(wellbore)
wellCat <- c()
for (well in wellbore){
  wellnum <- well[[length(well)]]
  wellCat <- append(wellCat, wellnum)
}
trainingCopy$wellbore_chev_no_id <- wellCat
wellseg <- str_split(trainingCopy$segment_id, '_')
segID <- c()
for (seg in wellseg){
  segnum <- seg[[length(seg)]]
  segID<- append(segID, segnum)
}
segID
trainingCopy$segment_id <- segID
trainingCopy
wellarea <- str_split(trainingCopy$area_id, '_')
areaID <- c()
for (area in wellarea){
  areanum <- area[[length(area)]]
  areaID<- append(areaID, areanum)
}
areaID
trainingCopy$area_id <- areaID
wellform <- str_split(trainingCopy$formation_id, '_')
formID <- c()
for (form in wellform){
  formnum <- form[[length(form)]]
  formID<- append(formID, formnum)
}
formID
trainingCopy$formation_id <- formID
wellbit <- str_split(trainingCopy$bit_model_id, '_')
bitID <- c()
for (bit in wellbit){
  bitnum <- bit[[length(bit)]]
  bitID<- append(bitID, bitnum)
}
trainingCopy$bit_model_id <- bitID


trainingCopy <- transform(trainingCopy, segment_id=as.numeric(segment_id))
trainingCopy <- transform(trainingCopy, area_id=as.numeric(area_id))
trainingCopy <- transform(trainingCopy, formation_id=as.numeric(formation_id))
trainingCopy <- transform(trainingCopy, bit_model_id=as.numeric(bit_model_id))
```

#pairs plots 
```{r}
#?pairs()
View(trainingCopy)
pairs(trainingCopy[c("drillbit_size", "min_depth", "surface_weight_on_bit", "surface_rpm")])
cor.test(trainingCopy$surface_weight_on_bit, trainingCopy$surface_rpm)
#DON'T FORGET TO DO VIF
```

Visual Data Exploration
```{r echo=TRUE}
jpeg("sectionid.jpeg")
plot(trainingCopy$segment_id, trainingCopy$rate_of_penetration, col=trainingCopy$wellbore_chev_no_id,
     main = "Rate of Penetration (ROP) on Section ID", ylab = "ROP (feet/hour)", xlab = "Section ID",
     )
dev.off()
jpeg("wellborechev.jpeg")
plot(trainingCopy$wellbore_chev_no_id, trainingCopy$rate_of_penetration, col=trainingCopy$wellbore_chev_no_id, main = "Rate of Penetration (ROP) on Wellbore ID", ylab = "ROP (feet/hour)", xlab = "Wellbore ID")
dev.off()
jpeg("Area ID.jpeg")
plot(trainingCopy$area_id, trainingCopy$rate_of_penetration, col=trainingCopy$wellbore_chev_no_id, main = "Rate of Penetration (ROP) on Area ID", ylab = "ROP (feet/hour)", xlab = "Area ID")
dev.off()
jpeg("formation_id.jpeg")
plot(trainingCopy$formation_id, trainingCopy$rate_of_penetration, col=trainingCopy$wellbore_chev_no_id, main = "Rate of Penetration (ROP) on Formation ID", ylab = "ROP (feet/hour)", xlab = "Formation ID")
dev.off()
jpeg("bitmodel.jpeg")
plot(trainingCopy$bit_model_id, trainingCopy$rate_of_penetration, col=trainingCopy$wellbore_chev_no_id, main = "Rate of Penetration (ROP) on Bit Model ID ID", ylab = "ROP (feet/hour)", xlab = "Bit Model ID")
dev.off()
jpeg("drillbitsize.jpeg")
plot(trainingCopy$drillbit_size, trainingCopy$rate_of_penetration, col=trainingCopy$wellbore_chev_no_id, main = "Rate of Penetration (ROP) on Drillbit Size", ylab = "ROP (feet/hour)", xlab = "Drillbit Size")
dev.off()
jpeg("mindepth.jpeg")
plot(trainingCopy$min_depth, trainingCopy$rate_of_penetration, col=trainingCopy$wellbore_chev_no_id, main = "Rate of Penetration (ROP) on Minimum Depth", ylab = "ROP (feet/hour)", xlab = "Minimum Depth")
dev.off()
jpeg("maxdepth.jpeg")
plot(trainingCopy$max_depth, trainingCopy$rate_of_penetration, col=trainingCopy$wellbore_chev_no_id, main = "Rate of Penetration (ROP) on Maximum Depth", ylab = "ROP (feet/hour)", xlab = "Maximum Depth")
dev.off()
jpeg("surfaceweight.jpeg")
plot(trainingCopy$surface_weight_on_bit, trainingCopy$rate_of_penetration, col=trainingCopy$wellbore_chev_no_id, main = "Rate of Penetration (ROP) on Surface Weight on Bit", ylab = "ROP (feet/hour)", xlab = "Surface Weight")
dev.off()
jpeg("surfacerpm.jpeg")
plot(trainingCopy$surface_rpm, trainingCopy$rate_of_penetration, col=trainingCopy$wellbore_chev_no_id, main = "Rate of Penetration (ROP) on Surface RPM", ylab = "ROP (feet/hour)", xlab = "Surface RPM")
dev.off()
```

```{r echo=TRUE}
install.packages("dplyr")
library(dplyr)
well24 <- trainingCopy %>% 
  filter(trainingCopy$wellbore_chev_no_id == 24)
plot(well24$segment_id, well24$rate_of_penetration, col=well24$wellbore_chev_no_id)
plot(well24$wellbore_chev_no_id, well24$rate_of_penetration, col=well24$wellbore_chev_no_id)
plot(well24$area_id, well24$rate_of_penetration, col=well24$wellbore_chev_no_id)
plot(well24$formation_id, well24$rate_of_penetration, col=well24$wellbore_chev_no_id)
plot(well24$bit_model_id, well24$rate_of_penetration, col=well24$wellbore_chev_no_id)
plot(well24$drillbit_size, well24$rate_of_penetration, col=well24$wellbore_chev_no_id)
plot(well24$min_depth, well24$rate_of_penetration, col=well24$wellbore_chev_no_id)
plot(well24$max_depth, well24$rate_of_penetration, col=well24$wellbore_chev_no_id)
plot(well24$surface_weight_on_bit, well24$rate_of_penetration, col=well24$wellbore_chev_no_id)
plot(well24$surface_rpm, well24$rate_of_penetration, col=well24$wellbore_chev_no_id)
hist(well24$rate_of_penetration)
```

```{r echo=TRUE}
well15 <- trainingCopy %>% 
  filter(trainingCopy$wellbore_chev_no_id == 15)
plot(well15$segment_id, well15$rate_of_penetration, col=well15$wellbore_chev_no_id)
plot(well15$wellbore_chev_no_id, well15$rate_of_penetration, col=well15$wellbore_chev_no_id)
plot(well15$area_id, well15$rate_of_penetration, col=well15$wellbore_chev_no_id)
plot(well15$formation_id, well15$rate_of_penetration, col=well15$wellbore_chev_no_id)
plot(well15$bit_model_id, well15$rate_of_penetration, col=well15$wellbore_chev_no_id)
plot(well15$drillbit_size, well15$rate_of_penetration, col=well15$wellbore_chev_no_id)
plot(well15$min_depth, well15$rate_of_penetration, col=well15$wellbore_chev_no_id)
plot(well15$max_depth, well15$rate_of_penetration, col=well15$wellbore_chev_no_id)
plot(log(well15$surface_weight_on_bit), well15$rate_of_penetration, col=well15$wellbore_chev_no_id)
plot(log(well15$surface_rpm), well15$rate_of_penetration, col=well15$wellbore_chev_no_id)
```


```{r echo=TRUE}
trainingArea0 <- trainingCopy %>% 
  filter(trainingCopy$area_id == 0)
trainingArea1 <- trainingCopy %>% 
  filter(trainingCopy$area_id == 1)
plot(trainingArea0$segment_id, trainingArea0$rate_of_penetration, col=trainingArea0$wellbore_chev_no_id)
plot(trainingArea0$wellbore_chev_no_id, trainingArea0$rate_of_penetration, col=trainingArea0$wellbore_chev_no_id)
plot(trainingArea0$area_id, trainingArea0$rate_of_penetration, col=trainingArea0$wellbore_chev_no_id)
plot(trainingArea0$formation_id, trainingArea0$rate_of_penetration, col=trainingArea0$wellbore_chev_no_id)
plot(trainingArea0$bit_model_id, trainingArea0$rate_of_penetration, col=trainingArea0$wellbore_chev_no_id)
plot(trainingArea0$drillbit_size, trainingArea0$rate_of_penetration, col=trainingArea0$wellbore_chev_no_id)
plot(trainingArea0$min_depth, trainingArea0$rate_of_penetration, col=trainingArea0$wellbore_chev_no_id)
plot(trainingArea0$max_depth, trainingArea0$rate_of_penetration, col=trainingArea0$wellbore_chev_no_id)
plot(trainingArea0$surface_weight_on_bit, trainingArea0$rate_of_penetration, col=trainingArea0$wellbore_chev_no_id)
plot(trainingArea0$surface_rpm, trainingArea0$rate_of_penetration, col=trainingArea0$wellbore_chev_no_id)

plot(trainingArea1$segment_id, trainingArea1$rate_of_penetration, col=trainingArea1$wellbore_chev_no_id)
plot(trainingArea1$wellbore_chev_no_id, trainingArea1$rate_of_penetration, col=trainingArea1$wellbore_chev_no_id)
plot(trainingArea1$area_id, trainingArea1$rate_of_penetration, col=trainingArea1$wellbore_chev_no_id)
plot(trainingArea1$formation_id, trainingArea1$rate_of_penetration, col=trainingArea1$wellbore_chev_no_id)
plot(trainingArea1$bit_model_id, trainingArea1$rate_of_penetration, col=trainingArea1$wellbore_chev_no_id)
plot(trainingArea1$drillbit_size, trainingArea1$rate_of_penetration, col=trainingArea1$wellbore_chev_no_id)
plot(trainingArea1$min_depth, trainingArea1$rate_of_penetration, col=trainingArea1$wellbore_chev_no_id)
plot(trainingArea1$max_depth, trainingArea1$rate_of_penetration, col=trainingArea1$wellbore_chev_no_id)
plot(trainingArea1$surface_weight_on_bit, trainingArea1$rate_of_penetration, col=trainingArea1$wellbore_chev_no_id)
plot(trainingArea1$surface_rpm, trainingArea1$rate_of_penetration, col=trainingArea1$wellbore_chev_no_id)
summary(lm(trainingArea0$rate_of_penetration ~ trainingArea0$surface_weight_on_bit))
```

Forward Stepwise Selection 
```{r echo=TRUE}
regressors <- colnames(trainingCopy)
regressors <- regressors[-c(2,3,8,9)]
tempbestR2 <- 0
tempbestmodel <- 0
for (xreg in regressors){
  tempLm <- lm(trainingCopy$rate_of_penetration ~ trainingCopy[[xreg]])
  if (summary(tempLm)$adj.r.squared > tempbestR2){
   tempbestR2 <- summary(tempLm)$adj.r.squared}
}
print(regressors)
regressors <- regressors[-7]
tempbestR2
for (xreg in regressors){
  print(xreg)
  tempLm <- lm(trainingCopy$rate_of_penetration ~ trainingCopy[[xreg]] + trainingCopy$surface_rpm)
  if (summary(tempLm)$adj.r.squared > tempbestR2){
   tempbestR2 <- summary(tempLm)$adj.r.squared}
}
tempbestR2
print(regressors)
regressors <- regressors[-6]
for (xreg in regressors){
  print(xreg)
  tempLm <- lm(trainingCopy$rate_of_penetration ~ trainingCopy[[xreg]] + trainingCopy$surface_rpm +trainingCopy$surface_weight_on_bit)
  if (summary(tempLm)$adj.r.squared > tempbestR2){
   tempbestR2 <- summary(tempLm)$adj.r.squared}
}
tempbestR2
print(regressors)
regressors <- regressors[-5]
for (xreg in regressors){
  print(xreg)
  tempLm <- lm(trainingCopy$rate_of_penetration ~ trainingCopy[[xreg]] + trainingCopy$surface_rpm +trainingCopy$surface_weight_on_bit + trainingCopy$min_depth)
  if (summary(tempLm)$adj.r.squared > tempbestR2){
   tempbestR2 <- summary(tempLm)$adj.r.squared}
}
tempbestR2
```

```{r echo=TRUE}
predicted <- predict(lm(trainingCopy$rate_of_penetration ~ trainingCopy$bit_model_id + trainingCopy$surface_rpm +trainingCopy$surface_weight_on_bit + trainingCopy$min_depth), trainingCopy)
rmse(trainingCopy$rate_of_penetration, predicted)
```



